### ISSUE TITLE
Exception: http code 403 in https://fe.smotreshka.tv/login

### ISSUE THREAD

**Issue by xxxDZxxx** [dev-cdmm/iptv.smotreshka#2]
Подскажите, у меня через php-cli вот такая печаль с основным index.php
` x2@user:~/test/iptv.smotreshka$ php index.php 
PHP Warning:  Module "curl" is already loaded in Unknown on line 0
Exception: http code 403 in https://fe.smotreshka.tv/login`

и вот такое с плейлистом...
`x2@user:~/test/iptv.smotreshka/xmltv$ php index.php 
PHP Warning:  Module "curl" is already loaded in Unknown on line 0
Exception: http code 403 in https://fe.smotreshka.tv/login
PHP Warning:  file_get_contents(xmltv.channels.xml): Failed to open stream: No such file or directory in /home/x2/test/iptv.smotreshka/xmltv/index.php on line 97
PHP Fatal error:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /home/x2/test/iptv.smotreshka/xmltv/index.php:97
Stack trace:
#0 /home/x2/test/iptv.smotreshka/xmltv/index.php(97): fwrite()
#1 /home/x2/test/iptv.smotreshka/xmltv/index.php(117): generate()
#2 /home/x2/test/iptv.smotreshka/xmltv/index.php(121): initSmotreshka()
#3 {main}
  thrown in /home/x2/test/iptv.smotreshka/xmltv/index.php on line 97`

**Comment by dev-cdmm** [comment]
Получаю такую ошибку, только когда не заполнены данные в:
```
 initSmotreshka("login","password","index.m3u8");
 ```
В index.php и xmltv/index.php вместо `login` и `password` нужно добавить свои авторизационные данные от Смотрешки.
